# Generated by Django 6.0.6 on 2026-06-23 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Jina la Nyumba/Hosteli')),
                ('description', models.TextField(verbose_name='Maelezo ya Jumla ya Nyumba')),
                ('location', models.CharField(choices=[('mazimbu', 'Mazimbu (Main Campus Area)'), ('moringe', 'Edward Moringe Campus Area'), ('chang_ombe', "Chang'ombe"), ('kingolwira', 'Kingolwira'), ('town', 'Morogoro Town')], default='mazimbu', max_length=50, verbose_name='Eneo Ilipo')),
                ('address', models.CharField(max_length=255, verbose_name='Anwani ya Karibu')),
                ('image', models.ImageField(upload_to='house_images/', verbose_name='Picha ya Nje ya Nyumba')),
                ('is_available', models.BooleanField(default=True, verbose_name='Ipo Wazi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('master', 'Master Bedroom (Choo ndani)'), ('single', 'Single Room (Kawaida - Choo cha nje)'), ('double', 'Double Room (Chumba kikubwa/Sebule)')], max_length=20, verbose_name='Aina ya Chumba')),
                ('price', models.IntegerField(verbose_name='Bei ya Chumba hiki')),
                ('room_image', models.ImageField(upload_to='room_images/', verbose_name='Picha ya Ndani ya Chumba')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sifa za ziada (mfano: Kina feni, vigae)')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='houses.house', verbose_name='Inapatikana kwenye Nyumba gani?')),
            ],
        ),
    ]
